version: "3"
services:
  standup_api:
    container_name: standup_api
    image: standup_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    networks:
      - standup_net
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - standup_net
networks:
  standup_net:
